{% set name = "session-info2" %}
{% set version = "0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/session_info2-{{ version }}.tar.gz
  sha256: e925d34d0a298afe19421d55287e8fb9ace3c8f6390832aa11c641f01bab4177

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatch-docstring-description
    - hatch-vcs
    - hatchling
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - session_info2
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/flying-sheep/session-info2
  dev_url: https://github.com/flying-sheep/session-info2
  doc_url: https://session-info2.readthedocs.io/
  summary: Print versions of imported packages.
  license: MPL-2.0
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - flying-sheep
